try{
    throw "myException";
}catch(e){
    console.log(e);
}